// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggcMZUqZ5qbW6lwCU81FdAZKZEZh_yYY',
    appId: '1:331563669835:web:cde22f495f7d54bc6df0ce',
    messagingSenderId: '331563669835',
    projectId: 'flash-chat-1f7f0',
    authDomain: 'flash-chat-1f7f0.firebaseapp.com',
    storageBucket: 'flash-chat-1f7f0.appspot.com',
    measurementId: 'G-JSHB3S7GVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmZU1T5TGVev_7x_8RJ47W_Yueax6eEPo',
    appId: '1:331563669835:android:61aeba9a7cdc20816df0ce',
    messagingSenderId: '331563669835',
    projectId: 'flash-chat-1f7f0',
    storageBucket: 'flash-chat-1f7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5OCd5rtk9YIH3yUq1f4P1sBkDa8v-_BA',
    appId: '1:331563669835:ios:7cd610575dbc9eb76df0ce',
    messagingSenderId: '331563669835',
    projectId: 'flash-chat-1f7f0',
    storageBucket: 'flash-chat-1f7f0.appspot.com',
    iosClientId: '331563669835-e5tj5itlcca2osnq1be0kkge8u07cmhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject9Firechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5OCd5rtk9YIH3yUq1f4P1sBkDa8v-_BA',
    appId: '1:331563669835:ios:7cd610575dbc9eb76df0ce',
    messagingSenderId: '331563669835',
    projectId: 'flash-chat-1f7f0',
    storageBucket: 'flash-chat-1f7f0.appspot.com',
    iosClientId: '331563669835-e5tj5itlcca2osnq1be0kkge8u07cmhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject9Firechat',
  );
}
